version: "3"

services:
  app:
    image: leoncz/cherry:latest
    privileged: True
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
